import { Rubik } from 'next/font/google'
import Link from 'next/link'
import './globals.css'
import Navbar from './components/Navbar'

const rubik = Rubik({
  weight: '900',
  subsets: ['latin'],
})

export const metadata = {
  title: 'ULL Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} mt-12`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
